# Generated by Django 4.0 on 2022-01-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_about', models.CharField(max_length=200)),
                ('movie_release', models.BooleanField(default=True)),
            ],
        ),
    ]
