# Generated by Django 4.0 on 2022-01-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_release',
            new_name='movie_released',
        ),
    ]
