# Generated by Django 4.0 on 2022-01-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteTitle', models.CharField(max_length=20)),
                ('noteContent', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorName', to='auth.user')),
            ],
            options={
                'verbose_name': 'Note Storage',
                'verbose_name_plural': 'Notes Storage',
            },
        ),
    ]
