# Generated by Django 4.0 on 2022-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allNotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notestorage',
            name='author',
        ),
    ]
