# Generated by Django 4.0 on 2022-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allNotes', '0003_alter_notemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
